name: Manual Deploy to Render

on:
  workflow_dispatch:  # Adds a 'Run workflow' button in GitHub Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST https://api.render.com/deploy/${{d1l5b66r433s73d9n73g/deploys/dep-d1l5b6er433s73d9n790 }}?key=${{2CCDE8rp1luoHfSBub5vbnFUfTBh}}
